services:
  app:
    build: .
    container_name: multi-agent-chatbot
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python vector_store.py &&
             uvicorn main:app --host 0.0.0.0 --port 8000 &
             streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0"